### ISSUE TITLE
[dev] On change, dev enters never-ending rebuild cycle

### ISSUE THREAD

**Issue by yet-another-dev** [cloudflare/wrangler#1078]
@EverlastingBugstopper

#### Environment

* operating system: MacOS (Catalina, 10.15.1)
* output of `rustc -V`: n/a
* output of `node -v`: v10.17.0
* output of `wrangler -V`: 1.8.0-rc.0

#### Steps to reproduce

Start workers dev (`wrangler dev`). Save the workers' entry file (e.g. `index.js`).

#### What did you expect to see?

The worker should rebuild once and then `dev` should be in watch mode.

#### What did you see instead?

The worker rebuilds once, then again, and agin, etc... never ending. 

Saving a worker's file results in a never-ending loop:

![image](https://user-images.githubusercontent.com/56443891/74688764-7e559d00-518d-11ea-961e-21741dd6a404.png)
 
#### Notes (maybe relevant): 
- This is for a workers site
- (Most of the time) `console.log`s are not showing in the terminal when the worker is called (i.e. when refreshing the page viewing the local worker's site). Can create a separate issue for this if need be.

**Comment by xtuc** [comment]
Could you please share your wrangler configuration (please remove zone/account info)? and webpack if you are using it?

**Comment by yet-another-dev** [comment]
Sure thing:

`wrangler.toml`
```toml
name = "dev"
type = "webpack"
# account_id = [removed for privacy]
workers_dev = true

[site]
bucket = "./dist"
entry-point = "./workers-site"

[env.production]
name = "production"
route = "www.my-domain.com/*" # changed for privacy
# zone_id = [removed for privacy]
```

Also, I've just tested on a non Workers Sites worker and am _not_ seeing this problem.
