### ISSUE TITLE
text binding is not creating in env

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#1081]
#### Environment

* operating system:
* output of `rustc -V`:
* output of `node -v`:
* output of `wrangler -V`:  wrangler 1.8.0-rc.0

#### Steps to reproduce

Wrangler configuration:
```toml
name = "hein"
type = "webpack"
webpack_config = "webpack.config.test.js"

[env.development]
text = { A = "1" }
```

```js
console.log(A)
```

#### What did you expect to see?

```js
console.log("1")
```

which you can get with the the Wrangler configuration:
```toml
name = "hein"
type = "webpack"
webpack_config = "webpack.config.test.js"
text = { A = "1" }

[env.development]
text = { A = "1" }
```

#### What did you see instead?

```
A is not defined
```
