### ISSUE TITLE
Provide better error message when API token doesn't have permissions

### ISSUE THREAD

**Issue by lukin0110** [cloudflare/wrangler#1157]
When I'm using the `apiToken` the Github Actions build fails with:
```
Error: Your user configuration is invalid, please run wrangler config and enter a new set of credentials.
```

This doesn't work for my repo:
```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
```

I switched to using the **Global Key**. Cfr: https://github.com/MakeInBelgium/naaiactie/
