### ISSUE TITLE
"expected a table key" error when configuring vars on wrangler.toml

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1159]
### 🐛 Bug Report

According to the docs this is how `vars` should be defined:
```
vars = {
  FOO = "0f2ac74b498b48028cb68387c421e279",
  BAR = "068c101e168d03c65bddf4ba75150fb0"
}
```
https://developers.cloudflare.com/workers/tooling/wrangler/configuration

But this produces the error:

> Error: expected a table key, found a newline at line 7 column 9 in wrangler.toml

Putting everything in a single line solves it... but it's pretty ugly.

```
vars = { FOO = "0f2ac74b498b48028cb68387c421e279", BAR = "068c101e168d03c65bddf4ba75150fb0"}
```

#### Environment

* operating system: macOS
* output of `node -v`: `v12.16.1`
* output of `wrangler -V`: `wrangler 1.8.1`

**Comment by EverlastingBugstopper** [comment]
Hey @PierBover - there are two different ways to define tables in TOML, the one described in the docs is the [inline style](https://github.com/toml-lang/toml#inline-table). 

If you want to have them on multiple lines you should be able to follow [this also valid style](https://github.com/toml-lang/toml#table):

```toml
[vars]
FOO = "1234"
BAR = "5678"
```

**Comment by PierBover** [comment]
Thanks @EverlastingBugstopper !

You should probably update those docs though...

**Comment by delphaber** [comment]
But it seems not working when using environments :(

```toml
[env.staging]
  [vars]
    FOO = "bar"

[env.production]
  [vars]
    FOO = "baz"
```

```bash
$ wranger build -e staging
# Error: redefinition of table `vars` for key `vars` at line XX column X in wrangler.toml
```

**Comment by EverlastingBugstopper** [comment]
@delphaber you'll need to define like so

```toml
[env.staging.vars]
FOO = "bar"

[env.production.vars]
FOO="baz"
```

the error you're seeing is because your TOML is invalid - you can copy and paste your toml file [here](https://www.toml-lint.com/) and see that it gives you a very similar error
