### ISSUE TITLE
Automatically run command prior to wrangler publish via toml value

### ISSUE THREAD

**Issue by mrw** [cloudflare/wrangler#1224]
#### Overview and problem statement

I think it'd be helpful for us Workers Sites users if `wrangler.toml` allowed a "pre-publish" command to be set.

In my case I'm using Jekyll to generate the static files prior to publishing with wrangler. When running `jekyll build` for production, we'll often include different command line variables or Jekyll config than we do locally/on staging so the output is optimized for production. It'd be great if wrangler allowed a "pre-publish" command to be set so it automatically runs the proper Jekyll build command before publishing.

#### Basic example

In `wrangler.toml`, something like this:

```toml
[site]
bucket = "./_site"
entry-point = "workers-site"
pre-publish = "jekyll build --config ./jekyll-production-config.yml"
```

Thanks for your consideration!
