### ISSUE TITLE
Wrangler is not installed properly in gitlab ci through npm

### ISSUE THREAD

**Issue by dephiros** [cloudflare/wrangler#1234]
#### Environment

* operating system: gitlab ci node:12
* output of `rustc -V`:
* output of `node -v`:v12.16.3
* output of `wrangler -V`:
* contents of `wrangler.toml`

#### Steps to reproduce
- Create a package.json with @cloudflare/wrangler as a dep
Create an .gitlab-ci.yml with the following content
```
image: node:12

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn config set cache-folder .yarn

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn
    - wrangler
```

#### What did you expect to see?
- The build should work correctly

#### What did you see instead?
```
 /node_modules/binary-install/src/binary.js:60
       throw `You have not installed ${this.name ? this.name : "this package"}`;
       ^
You have not installed wrangler
 (Use `node --trace-uncaught ...` to show where the exception was thrown)
 Task completed in 0m0.096s
Running after_script
00:01
Uploading artifacts for failed job
00:02
 ERROR: Job failed: exit code 1
```
