### ISSUE TITLE
Somehow I wrote 2 values with same key

### ISSUE THREAD

**Issue by amio** [cloudflare/wrangler#1308]
### 🐛 Bug Report

Now it's two kv pairs in the storage, with same key:

![image](https://user-images.githubusercontent.com/215282/82543549-4db74200-9b86-11ea-9c05-8528c8b83646.png)

From wrangler cli it returns first value:

```
$ wrangler kv:key get --binding OPENKV /public/ad3c14d6-2efc-498c-a4b7-a394dc384682-lasest-version
{"v":"1.2.3","t":""}
```

#### Environment

* operating system: OS X 10.15.4
* output of `rustc -V`: 1.43.1
* output of `node -v`: 14.0.0
* output of `wrangler -V`: 1.9.0
* contents of `wrangler.toml`:

```toml
name = "kv"
type = "webpack"
account_id = "ab4c068c2a00f246b30cd3a20859ca51"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv-namespaces = [
  { binding = 'OPENKV', id = 'df7d2685fc034190aa3a79adcec9d435' }
]
```

#### Steps to reproduce

I'm not sure how it happens.

#### What did you expect to see?

The key shouldn't be duplicated

#### What did you see instead?

Two kv pairs with same key name.
