### ISSUE TITLE
"javascript" worker site is still using webpack

### ISSUE THREAD

**Issue by jdanyow** [cloudflare/wrangler#1321]
### 🐛 Bug Report

I'm using the `javascript` type in my wrangler.toml but wrangler still runs webpack on my script. 

There are similar issues where folks from Cloudflare have stated this would be a bug:
https://github.com/cloudflare/wrangler/issues/1287#issuecomment-631097951

#### Environment

* ubuntu
* node v13.14.0
* wrangler 1.9.1

```toml
name = "xxxx-dev"
type = "javascript"
zone_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
route = "dev.xxxx.com/*"
workers_dev = false

[site]
bucket = "./packages/public/dist"
entry-point = "./packages/worker"
# :point_up: this folder has a package.json with "main":"dist/index.js" (already bundled with rollup)

[env.staging]
name = "xxxx-staging"
route = "staging.xxxx.com/*"

[env.production]
name = "xxxx-production"
route = "xxxx.com/*"
```

#### Steps to reproduce

`wrangler publish` results in the following output:
```
✔ ~/repos/xxxx [master L|…1] 
22:27 $ wrangler publish
 Built successfully, built project size is 13 KiB.
 Using namespace for Workers Site "__xxxx-dev-workers_sites_assets"
 Success
 Deployed to the following routes:
dev.xxxx.com/* => stayed the same
```
A new folder is added under my existing `./packages/worker` folder. The new folder is called `worker` and contains a single file, `script.js` with what appears to be the result of webpacking my `packages/worker/dist/index.js` file.

I expected wrangler to publish my `packages/worker/dist/index.js` file as-is, and not create a new folder.
