### ISSUE TITLE
[dev] return granular API error messages

### ISSUE THREAD

**Issue by jahands** [cloudflare/wrangler#1330]
### 🐛 Bug Report
Wrangler Dev command won't work if Cloudflare API is down, is there a technical reason to require something from the Cloudflare API for testing locally?

#### Environment

* operating system:
WSL1 on Windows 10
* output of `rustc -V`:
Not installed
* output of `node -v`:
v8.10.0
* output of `wrangler -V`:
wrangler 1.9.0-rc.1
* contents of `wrangler.toml`
```toml
name = "workers-multiapp-example"
type = "webpack"
account_id = "f9b1e1e2cf50cca79a58e395b6084239"
workers_dev = true
route = ""
zone_id = "93f68d5e5674aaeab0d492c8fbc31fee"
webpack_config = "webpack.config.js"
kv-namespaces = [
         { binding = "MY_KV", id = "e29b263ab50e42ce9b637fa8370175e8" }
]
```
#### Steps to reproduce
Run `wrangler dev` when the API is down

#### What did you expect to see?
Local environment running worker
#### What did you see instead?
Error: Could not upload your script. Check your internet connection or https://www.cloudflarestatus.com/ for rare incidents impacting the Cloudflare Workers API.
