### ISSUE TITLE
Pushing a secret for a new worker fails

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1418]
#### Environment

* operating system: Darwin C02CHCUPMD6R 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
* output of `rustc -V`: 1.43.1
* output of `node -v`: 10.21.0
* output of `wrangler -V`: 1.9.2
* contents of `wrangler.toml`
```toml
name = "test"
type = "javascript"
account_id = "8096b46048b3aecd5184b594f3c5db0a"
workers_dev = true
route = ""
zone_id = "54d9876e41ed2a44f803602b79245aa5"
```

#### Steps to reproduce

With the following worker:

```js
const secret = SECRET

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  return new Response(`Psst!  The secret is ${secret}!`, {
    headers: { 'content-type': 'text/plain' },
  })
}
```

Trying to create/push secrets doesn't work:

```console
$ echo 'secret' | wrangler secret put SECRET
Enter the secret text you'd like assigned to the variable SECRET on the script named test:
🌀  Creating the secret for script name test
🌀  Worker test doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught ReferenceError: SECRET is not defined\n  at line 1\n"
    }
  ],
  "messages": []
}
```
