### ISSUE TITLE
Access is denied (os error 5) on occurs when "wrangler generate" is used in Windows 10

### ISSUE THREAD

**Issue by RobinCodeX** [cloudflare/wrangler#1504]
#### Environment

* operating system: Windows 10 2004
* output of `rustc -V`: 1.45.2 (d3fb005a3 2020-07-31)
* output of `node -v`: v12.13.0
* output of `wrangler -V`: 1.10.3
* contents of `wrangler.toml`: None

#### Steps to reproduce

```
PS > wrangler generate --site my-site
  Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
Access is denied. (os error 5)
PS > cargo install cargo-generate
    Updating crates.io index
     Ignored package `cargo-generate v0.5.0` is already installed, use --force to override
```

https://community.cloudflare.com/t/how-to-solve-access-is-denied-os-error-5-on-wrangler-generate/197931

**Comment by EverlastingBugstopper** [comment]
@RobinCodeX - the team is unable to reproduce this error. How do you have node installed? This seems like a permissions error and this can happen if you haven't installed node with a version manager like [nodist](https://github.com/nullivex/nodist)

**Comment by RobinCodeX** [comment]
@EverlastingBugstopper Yes, I have installed node.
Now, I have reinstalled node by nodist, node version is 14.8.0,
However, this problem still exists and I run in administrator mode.
I don’t understand what causes this permission problem. 
Even in administrator mode, I still have this permission problem, but I can run it correctly in WSL.

**Comment by RobinCodeX** [comment]
I found the error throw in https://github.com/cloudflare/wrangler/blob/e32fc6c13c46bc8b92bc22a2bcbe58bdceb72133/src/install/mod.rs#L129-L130

I checked the cache folder and it was successfully downloaded and unzipped.
![image](https://user-images.githubusercontent.com/8408783/93704954-8cb4ce80-fb4b-11ea-9cd3-d118b2f60dcd.png)
![image](https://user-images.githubusercontent.com/8408783/93704948-7eff4900-fb4b-11ea-9037-2fbfe14e1270.png)

It looks like an error from the `binary-install` library.
https://github.com/rustwasm/binary-install/blob/77114ac51b442341a0977122eeea260c6d0262c2/src/lib.rs#L158-L160

This seems to be a permission error, but I can be sure that there is no problem with the read and write permissions
```
PS C:\Users\robin> wrangler generate my-worker
  Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
Access is denied. (os error 5)
```

**Comment by zhb124404** [comment]
I've met the issue,too
![image](https://user-images.githubusercontent.com/16805041/93991926-7a42cb00-fdbf-11ea-9f4a-3d869aef34f2.png)

**Comment by zhb124404** [comment]
> I found the error throw in
> 
> https://github.com/cloudflare/wrangler/blob/e32fc6c13c46bc8b92bc22a2bcbe58bdceb72133/src/install/mod.rs#L129-L130
> 
> I checked the cache folder and it was successfully downloaded and unzipped.
> ![image](https://user-images.githubusercontent.com/8408783/93704954-8cb4ce80-fb4b-11ea-9cd3-d118b2f60dcd.png)
> ![image](https://user-images.githubusercontent.com/8408783/93704948-7eff4900-fb4b-11ea-9037-2fbfe14e1270.png)
> 
> It looks like an error from the `binary-install` library.
> https://github.com/rustwasm/binary-install/blob/77114ac51b442341a0977122eeea260c6d0262c2/src/lib.rs#L158-L160
> 
> This seems to be a permission error, but I can be sure that there is no problem with the read and write permissions
> 
> ```
> PS C:\Users\robin> wrangler generate my-worker
>   Installing cargo-generate v0.5.0...
> Error: could not download `cargo-generate`
> Access is denied. (os error 5)
> ```

I find a way to resolve it temporarily.
Just rename the '.cargo-generate-0.5.0' to 'cargo-generate-0.5.0'
![image](https://user-images.githubusercontent.com/16805041/94113895-28ab4680-fe7a-11ea-9439-8e95212b0bab.png)

and then wrangler works.
![image](https://user-images.githubusercontent.com/16805041/94114003-52646d80-fe7a-11ea-8c28-7380dd289f6c.png)

**Comment by lisonge** [comment]
# same error

![image](https://user-images.githubusercontent.com/38517192/94344064-5dbcc200-004f-11eb-84df-d6e776a2991b.png)

**Comment by lisonge** [comment]
you can generate you project on linux, then download artifact to develop on windows

the npm run-script * is available on windows

```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo npm install -g @cloudflare/wrangler
          sudo wrangler generate project-name https://github.com/EverlastingBugstopper/worker-typescript-template
          ls -R
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-dist
          path: project-name
```
