### ISSUE TITLE
Regression: cannot start a local unauthenticated dev server without an account id in wrangler.toml

### ISSUE THREAD

**Issue by 0dinD** [cloudflare/wrangler#1525]
#### Environment

* operating system: Linux (Debian 10 Buster)
* output of `rustc -V`: N/A
* output of `node -v`: v14.8.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.11.0
* contents of `wrangler.toml`:
```toml
name = "test"
type = "javascript"
workers_dev = true
```

#### Steps to reproduce
1. Create a valid worker
2. Run `wrangler dev`

#### What did you expect to see?
```
💁  Running preview without authentication.
💁  watching "./"
👂  Listening on http://127.0.0.1:8787
```

#### What did you see instead?
```
Error: field `account_id` is required to deploy to workers.dev
```

#### Further comments
This is a regression from wrangler 1.10, where no account id was required in wrangler.toml. I don't think it should be required if you don't want to authenticate and just want to run the worker on your local machine for quick development and testing. 

The `dev` command actually does work as expected if you supply an account id in wrangler.toml, but it doesn't even have to be valid as it's clearly not used when you don't authenticate. So the following is a workaround:
```toml
name = "test"
type = "javascript"
workers_dev = true
account_id = "not_a_valid_id"
```
