### ISSUE TITLE
Mini RFC: Cron Triggers

### ISSUE THREAD

**Issue by ObsidianMinor** [cloudflare/wrangler#1574]
Cron triggers are out, but there isn't a way to configure them from wrangler. To support cron triggers, I propose we add a new `triggers` table with a `crons` field as an array of strings.

### Example

```toml
name = "scheduled"
type = "javascript"
account_id = "..."

[triggers]
crons = ["* * * * *"]
```

```toml
name = "weekly"
type = "javascript"
account_id = "..."

[triggers]
crons = ["0 0 * JAN-JUN FRI", "0 0 * JUL-DEC SAT"]
```
