### ISSUE TITLE
wrangler.toml -- support for 'type = "disabled"'

### ISSUE THREAD

**Issue by captain-kark** [cloudflare/wrangler#1668]
### 💡 Feature request

Support for workers which, when configured and "published" via wrangler, appear as "Disabled" in the UI.

![image](https://user-images.githubusercontent.com/46486335/101198978-8de29b80-3664-11eb-8eb7-612e2d29ff2c.png)

#### Overview and problem statement

I would like to include additional configuration for workers which operate on routes that have a very broad scope, such as `mysite.com/api/*` to manage specific routes which I know *do not* need to invoke not just the current worker, but *any worker*, in order to reduce unnecessary worker invocations.

#### Basic example

Currently, I must do this manually, or automate it via some light scripting. Although it's not that bad to manage this via the API, it'd be much nicer to get this type of feature in front of users so that it can ~~cut into your profit margins~~ optimize your bandwidth and mCPU utilization in your production environment 🙃 

It would be great to set this in [my `wrangler.toml` file](https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys) somehow, perhaps as an "environment".

> wrangler.toml

```toml
type = "webpack"
account_id = "..."
zone_id = "..."
name = "all-i-want-for-christmas-is-fetch-event-bubbling"
route = "mysite.com/api/*"

[env.disabled]
type = "disabled"
routes = ["mysite.com/api/.well-known/jwks", "mysite.com/api/customers/thatoneguy/*", "mysite.com/api/externalthing/*" ]
```

```
$: wrangler publish -e disabled
```

Or however you want to do it. The important part is that this information about disabled routes is contained next to the rest of my worker's source code. The bits where workers aren't running is just as important as where they do run!
