### ISSUE TITLE
Support uploading a pre-built WASM module

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler#1716]
#### Overview and problem statement

Right now, wrangler [supports the building a WASM module as part of the build and upload process with  `type = "rust"`](https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys), but does not support uploading a pre-built WASM module. I propose adding a new key to the wrangler configuration to allow developers to specify the filepath location of any modules they want to bind (similar to how they already specify the `webpack_config` location). I imagine it would work similar to `kv_namespaces`.

#### Basic example

```toml
# wrangler.toml
name = "$SCRIPT_NAME"
type = "webpack"
account_id = "$ACCOUNT_ID"
workers_dev = true

# Just as webpack config files are located like this,
webpack_config = "./webpack.config.js"

# and KV namespaces are configured in an array like this,
kv_namespaces = [
  { binding = "FOO", id = "0f2ac74b498b48028cb68387c421e279", preview_id = "6a1ddb03f3ec250963f0a1e46820076f" },
  { binding = "BAR", id = "068c101e168d03c65bddf4ba75150fb0", preview_id = "fb69528dbc7336525313f2e8c3b17db0" }
]

# WASM modules could be configured as follows:
wasm_modules = [
  { binding = "MYWASM", location = "./my_wasm_file.wasm" }
]
```

Wrangler would simply have to locate the file, reference it in the metadata, and upload it alongside the script as a part of the PUT call to upload a new worker.
