### ISSUE TITLE
JSON files included in the worker script

### ISSUE THREAD

**Issue by rubenamorim** [cloudflare/wrangler#1719]
### 🐛 Bug Report

JSON files are included in the worker script processed by the webpack.
This occurs in the `filterByExtension` function in `wranglerjs` because it evaluates to true with the `js` extension passed as an argument and matches for `js` and `json` files.

#### Environment

* operating system:
* output of `rustc -V`: 1.49.0
* output of `node -v`: 14.15
* output of `wrangler -V`: 1.12.3
* contents of `wrangler.toml`

```toml
account_id = "$CF_ACCOUNT_ID"
name = "example"
route = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
workers_dev = true
zone_id = ""

[site]
bucket = "out"
entry-point = "./"
```

#### Steps to reproduce

1. Create a worker site using the Flareact template: `wrangler generate my-project https://github.com/flareact/flareact-template`
2. Add a json file to the `public` folder to be served as a static asset
3. Build and deploy: `yarn deploy`

#### What did you expect to see?

The content of the JSON file is not included in the worker's script file.

#### What did you see instead?

The worker script file includes the content of the JSON file.

EDIT:

Here's an incorrectly generated script file and the attempt to publish it:

<img width="709" alt="Screenshot 2021-01-13 at 14 00 59" src="https://user-images.githubusercontent.com/19737508/104461994-f0a24d80-55a7-11eb-945d-96857b441d4f.png">
<img width="1227" alt="Screenshot 2021-01-13 at 14 01 10" src="https://user-images.githubusercontent.com/19737508/104461986-ee3ff380-55a7-11eb-8322-6511b68d7773.png">
