### ISSUE TITLE
wrangler dev often panics when it detects new files but keeps serving pages but doesn't pick up changes

### ISSUE THREAD

**Issue by jschlesser** [cloudflare/wrangler#1738]
#### Environment

* operating system: MacOS BigSur 11.1
* output of `rustc -V`: rustc: command not found
* output of `node -v`: v15.6.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.13.0
* contents of `wrangler.toml`
```toml
name = "...."
type = "webpack"
account_id = "...."
workers_dev = true
route = ""
zone_id = "...."
kv_namespaces = [
    { binding = 'CDIPFiles', id = "....", preview_id = "...." },
    { binding = 'SwellsKV', id = "....", preview_id = "...." }
]

[site]
bucket = "./public"

[dev]
ip="127.0.0.1"
port=8787
local_protocol="https"
upstream_protocol="https"

```

#### Steps to reproduce
There isn't anything special about my source tree.  Its a worker site and when I edit some html in the public directory with `wrangler dev` running, sometimes it panics.

#### What did you expect to see?
I expect to be able to reload my webpage and see changes.

#### What did you see instead?
The page loads but without seeing any changes.   Note that wrangler doesn't fully crash.   It looks to me like the 'watcher' thread has problems and stops seeing changes.   The main wrangler process seems to still be running and serving up 127.0.0.1:8787

It isn't for every change, just 'sometimes', but its fairly often.  Every 15 minutes.  The only remedy is to kill `wrangler dev` and restart it

Below is the panic:
```
🌀  Detected changes...
thread '<unnamed>' panicked at '--watch change message failed to send: "SendError(..)"', src/wranglerjs/mod.rs:111:41
stack backtrace:
   0:        0x106204c74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
   1:        0x10622b1a0 - core::fmt::write::h94ae1e793baa7a00
   2:        0x1061fca9b - std::io::Write::write_fmt::h5c716758fdc3057f
   3:        0x106206e95 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
   4:        0x106206bd7 - std::panicking::default_hook::heae8b62897b351dc
   5:        0x106207435 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
   6:        0x106206fcb - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
   7:        0x1062050e8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
   8:        0x106206f8a - _rust_begin_unwind
   9:        0x1062504df - core::panicking::panic_fmt::hcdc9362d34d55302
  10:        0x1062503e5 - core::result::unwrap_failed::h4cf11d46918a5fd4
  11:        0x1058b3b02 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf28b3c53cfbf081c
  12:        0x1059a18a3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h687aa541229da33d
  13:        0x1062103cd - std::sys::unix::thread::Thread::new::thread_start::hd4805e9612a32deb
  14:     0x7fff20363950 - __pthread_start
```
