### ISSUE TITLE
KV store is not available when running `wranger dev` with `--host` argument

### ISSUE THREAD

**Issue by grahamlyons** [cloudflare/wrangler#1866]
#### Describe the bug

When running `wrangler dev --host something.com` any KV stores are not available. Looks like it arises from #1498

#### Reproduce the bug

1. Create a worker project that uses a KV store
2. Create a KV store in Cloudflare
3. Add KV id to `preview_id` to be used locally
4. Ensure API token is available
5. Run `wrangler dev --host somehost.com`

#### Expected behavior

The local project should be able to use the KV store.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Debian
* output of `wrangler -V`: 1.15.0
* output of `node -v`: 14.16.0
* content of `wrangler.toml`:
```toml
name = "example"
type = "webpack"
account_id = "<id>"
workers_dev = true
zone_id = "<id>"
routes = [
    "https://world.dev-example.com/*",
    "https://hello.dev-example.com/*",
    "https://foo.dev-example.com/*",
]
zone_id = ""
kv_namespaces = [
  { binding = "KV_NAME", id = "<id>", preview_id = "<id>"}
]

[env.production]
zone_id = "<id>"
routes = [
    "https://world.example.com/*",
    "https://hello.example.com/*",
    "https://foo.example.com/*",
]
kv_namespaces = [
  { binding = "KV_NAME", id = "<id>", preview_id = "<id>"}
]
```
