### ISSUE TITLE
Forwarding wrangler port host -> guest doesn't seem to work using Docker

### ISSUE THREAD

**Issue by prof-dr1** [cloudflare/wrangler#1872]
#### Describe the bug

I'm not 100% sure if it's a bug, but this is the first time port forwarding doesn't work for me using docker.

#### Reproduce the bug

Setup Docker with the following config:

```
 node:
    image: node
    ports:
      - '8787:8787'
    command: sh -cx 'npm install @cloudflare/wrangler -g'
```
Start `wrangler dev`.

Now try to access http://localhost:8787 from your host, which doesn't seem to work. I've also tried it with `- '127.0.0.1:8787:8787'` in the ports config, but it doesn't help.

It only works when I add a user forwarded port with the vscode remote dev extension.

#### Expected behavior

http://localhost:8787 should be accessible from the host.

#### Environment and versions

* operating system: MacOS (host)
* output of `wrangler -V`: 1.16.0
* output of `node -v`: v15.11.0
* content of `wrangler.toml`:

```
name = "example"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "1234"
workers_dev = true
```
