### ISSUE TITLE
Workers Sites with custom webpack config

### ISSUE THREAD

**Issue by boojum** [cloudflare/wrangler#1927]
#### Describe the bug

As per the [documentation](https://developers.cloudflare.com/workers/cli-wrangler/webpack), I'm trying to setup a cf worker site with custom `webpack` config. The `type` and `webpack_config` options are set in `wrangler.toml`, as well as `bucket` and `entry-point`. Similarly, `context` and `entry` are set in `webpack.config.js`. Somehow, `webpack` is still returning an error

#### Reproduce the bug

1. Clone this [repo](https://gitlab.com/b00jum/cf-worker-site-typescript)
2. `cd cf-worker-site-typescript && npm install`
3. `npm run dev` (alias to `wrangler dev`)
4. Observe the error:
```
👀  ./src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/home/boojum/Projects/playground/mono/worker-site-webpack/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/home/boojum/Projects/playground/mono/worker-site-webpack/node_modules/ts-loader/dist/index.js:14:21)
Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
```

#### Expected behavior

I expect the project to be compiled & build correctly, then served through `wrangler dev` command.

#### Environment and versions

* operating system: ubuntu 21.04
* output of `wrangler -V`: wrangler 1.16.1
* output of `node -v`: v15.14.0
* content of `wrangler.toml`:
```toml
name = "worker-site"
type = "webpack"
webpack_config = "webpack.config.js"
workers_dev = true
account_id = ""
zone_id = ""

[site]
bucket = "public"
entry-point = '.'
```
