### ISSUE TITLE
__STATIC_CONTENT_MANIFEST missing in env object when using ES modules

### ISSUE THREAD

**Issue by ttraenkler** [cloudflare/wrangler#1938]
#### Describe the bug

When using the new ES module syntax and rollup instead of webpack as a bundler, I cannot access the workers-site binding `__STATIC_CONTENT_MANIFEST` neither through the global env variable anymore nor through the new env object.

I have tried using both wrangler 1.16.1 or 1.16.0-durable-objects-rc.0 to upload a workers-site with the same result

#### Reproduce the bug

A list of steps to reproduce the bug.

1. upload a workers-site with the latest wrangler 
2. bundle your worker with rollup using the new ESM syntax
3. try to access the `__STATIC_CONTENT_MANIFEST` as a global variable or in the `env` object -> is undefined

#### Expected behavior

```ts
env.__STATIC_CONTENT_MANIFEST
``` 
should contain the manifest string

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS latest
* output of `wrangler -V`: wrangler 1.16.0-durable-objects-rc.0
* output of `node -v`: v14.15.4
* content of `wrangler.toml`:

```toml
account_id = "..."
kv_namespaces = [...]
name = "..."
route = ""
type = "javascript"
vars = {ENVIRONMENT = "production", DEBUG_MODE = false}
workers_dev = true
zone_id = ""

[site]
bucket = "../build"
entry-point = "workers-site"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[build]
command = "yarn && yarn build"

[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
dir = "dist"
format = "modules"
main = "./index.mjs"

```

I think the relevant file should be `src/upload/form/mod.rs` in the wrangler repo.
Let me know if you need more information or cannot reproduce the bug without further details. Also please point me to a branch if there is already ongoing work so I could potentially contribute a PR.
