### ISSUE TITLE
wrangler report rejected with 405 error while logged in

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/wrangler#1954]
#### Describe the bug

Can't report crashes with wrangler. Hard to search Github for this issue because every issue contains "wrangler" and "report" :) - sorry if this is a dupe!

#### Reproduce the bug

A list of steps to reproduce the bug.

1. `wrangler whoami` (verify logged in status)
2. `wrangler report`
3. `Error: submission failed! please verify your credentials and try again. (status: 405 Method Not Allowed)`

#### Expected behavior

Expected `wrangler report` to successfully share debugging information with the wrangler team.

#### Environment and versions

* operating system: Big Sur 11.3.1
* output of `wrangler -V`: 1.17.0
* output of `node -v`: v16.2.0
* `wrangler.toml`

``` toml
name = <redacted>
type = "javascript"
account_id = <redacted>
workers_dev = true
route = ""
zone_id = ""
target_type = "js"
[vars]
ENVIRONMENT = "development"
CALLBACK_URI = <redacted>
HOME_URI = <redacted>

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.staging]
name = <redacted>
[env.staging.vars]
ENVIRONMENT = "staging"
CALLBACK_URI = <redacted>

[env.production]
name = <redacted>
route = <redacted>
zone_id = <redacted>
[env.production.vars]
ENVIRONMENT = "production"
CALLBACK_URI = <redacted>
HOME_URI = <redacted>
```
