### ISSUE TITLE
Wrangler silently fails while publishing worker site

### ISSUE THREAD

**Issue by jrf0110** [cloudflare/wrangler#1963]
#### Describe the bug

We started seeing wrangler silently fail to publish our site. It doesn't have any log output. It just exits. This started happening when we inlined all of our site's CSS into the <head> tag of each page (there's ~15k pages generated).

#### Expected behavior

wrangler publish should publish our assets to KV and update our worker.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Debian Buster
* wrangler version: `wrangler 1.16.1`
* node version: `12.18.*`
* content of `wrangler.toml`:

```toml
name = "www"
type = "webpack"
account_id = "..."
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = [ 
    { binding = "...", id = "..." },
    { binding = "...", id = "...", preview_id = "..." }
]

[env.production]
vars = { ENVIRONMENT = "production", BYPASS_AUTH = "false" }
kv_namespaces = [ 
    { binding = "...", id = "..." },
    { binding = "...", id = "...", preview_id = "..." }
]
zone_id = "..."
route = "www.example.com/*"
```
