### ISSUE TITLE
Wrangler not warning of no zone_id

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/wrangler#2044]
#### Describe the bug
I was attempting to deploy on my domain but not `workers.dev`. I disabled `workers_dev` and set `route` however I kept getting the same error:
> Error: Please specify your deployment routes or `wrangler_dev = true` inside of your configuration file. For more information, see: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys

I matched both the conditions here but my st00pid ass forgot to add `zone_id` which was preventing this from deploying. There should be an error message if `zone_id` is not set but `route` is set.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create a new Wrangler project
2. Set your `wrangler.toml` like this:
```toml
name = "wrangler-faq-backend"
account_id = "ACCOUNT_ID"
type = "javascript"
route = "test.example.com/*"
workers_dev = false
```
3. Attempt to publish - `wrangler publish`
4. Observe error:
> Error: Please specify your deployment routes or `wrangler_dev = true` inside of your configuration file. For more information, see: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys

#### Expected behavior
There is a clearer message saying that `zone_id` must be specified. Something like:
> Error: Please specify your deployment routes and `zone_id` or `workers_dev = true` inside of your configuration file. For more information, see: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys

#### Environment and versions

* operating system:
* output of `wrangler -V`: wrangler 1.19.0
* output of `node -v`: v16.6.2
* content of `wrangler.toml`:
```toml
name = "wrangler-faq-backend"
account_id = "ACCOUNT_ID"
type = "javascript"
route = "test.example.com/*"
workers_dev = false
```
