### ISSUE TITLE
WebSocket does not work with `wrangler dev`

### ISSUE THREAD

**Issue by mnixry** [cloudflare/wrangler#2079]
#### Describe the bug

Cloudflare Worker supports establish experimental WebSocket connection with users, which could work with production environment perfectly. But development server started by `wrangler dev` does not work.

With default config, we cannot built any WebSocket connection because worker cannot receive `Upgrade` header

Once set up configs below, Worker can receive `Upgrade` header and could establish a WebSocket connection, but it disconnected immediately

```toml
local_protocol = "http"
upstream_protocol = "http"
```

#### Reproduce the bug

Create a worker provides WebSocket server with [official demo](https://github.com/cloudflare/websocket-template/blob/main/index.js)

#### Environment and versions

Fill out the following information about your environment.

* operating system: Manjaro 21.1.4
* output of `wrangler -V`: wrangler 1.19.3-rc.1
* output of `node -v`: v16.9.1
* content of `wrangler.toml`:
```toml
name = "onebot-worker"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[dev]
local_protocol = "http"
upstream_protocol = "http"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
```
