### ISSUE TITLE
Wrangler gives confusing error when trying to use workers sites with durable objects

### ISSUE THREAD

**Issue by gzuidhof** [cloudflare/wrangler#2093]
#### Describe the bug

When first publishing a worker, and subsequently using `wrangler dev` or `wrangler publish` fails - something related to the migration tags.

In other words: it works once, then never again. Wish I had more info to go on.

```
Error: The migration tag for the script was never fetched. This is a bug in wrangler, and we'd appreciate an issue report!
```

#### Reproduce the bug

```toml
type = "javascript"
name = "beamerserver"
account_id = "..."
workers_dev = true
zone_id = "..."
compatibility_date = "2021-10-02"

[durable_objects]
bindings = [
  { name = "ROOM_DURABLE_OBJECT", class_name = "RoomDurableObject" },
  { name = "ROOM_HUB_DURABLE_OBJECT", class_name = "RoomHubDurableObject" },
  { name = "RATE_LIMITER_DURABLE_OBJECT", class_name = "RateLimiterDurableObject" },
]

[[migrations]]
tag = "m1" 
new_classes = ["RoomDurableObject", "RoomHubDurableObject", "RateLimiterDurableObject"] 

[build]
command = "npm run build"

[build.upload]
dir = "dist"
format = "modules"
main = "./worker.mjs"

[site]
entry-point = "./"
bucket = "./dist/static"
```

```
$ wrangler dev
 Running npm run build

> sunder-starter@0.1.0 build
> node build.js -sourcemap

Wrote dist/worker.mjs (100.3kB, 28.12ms)
Waiting for TypeScript... (^C to skip)
 Using namespace for Workers Site "__beamerserver-workers_sites_assets_preview"
 Success
Error: The migration tag for the script was never fetched. This is a bug in wrangler, and we'd appreciate an issue report!
```

#### Expected behavior
Publish or dev to work.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows 10
* output of `wrangler -V`: `wrangler 1.19.3`
* output of `node -v`: `v16.5.0`
* content of `wrangler.toml`: See above
