### ISSUE TITLE
403 Forbidden on `wrangler dev` with Durable Workers starter template

### ISSUE THREAD

**Issue by jakst** [cloudflare/wrangler#2154]
#### Describe the bug

I wanted to try out Durable Workers, but I'm getting this error when running `wrangler dev` when following [the guide](https://developers.cloudflare.com/workers/learning/using-durable-objects
). I haven't worked with wrangler, workers or durable objects before.

```
Error: HTTP status client error (403 Forbidden) for url (https://api.cloudflare.com/client/v4/accounts/<account_id>/workers/subdomain/edge-preview)
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run `wrangler generate test-durable-objects https://github.com/cloudflare/durable-objects-template`
2. Run `wrangler login` and authenticate
3. Add `account_id` to wrangler.toml
4. Run `wrangler dev`
5. Get the 403 error

#### Expected behavior

A dev environment is started.

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS 12.0.1
* output of `wrangler -V`: wrangler 1.19.5
* output of `node -v`: 16.13.0
* content of `wrangler.toml`: 
```toml
name = "test-durable-objects"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
account_id = "<account_id>"
route = ""
zone_id = ""
compatibility_date = "2021-12-09"

[build.upload]
# Upload the code directly from the src directory.
dir = "src"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]
```
