### ISSUE TITLE
RFC: introducing environments

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#220]
## Problem

As described https://github.com/cloudflare/wrangler/issues/199, we should have a way to configure Wrangler based on an environment name.

### New command line argument

I'm suggesting to add an `--env NAME` argument for `wrangler publish` and `wrangler build`. Additionally we could use an environment variable.

The build commande is included because a custom webpack configuration could take advantage of it to provide a specific configuration. However, to be able to access it we need to inject an environment variable called `WRANGLER_ENV`.

### Segmented configuration

I think that the entire configuration needs to be segmented by env, like the following example:

```toml
[env.prod]
name = "wasm-worker-prod"
zone_id = "zone-prod"
account_id = "account-prod"
route = "https://prod.site"
kv-namespaces = ...

[env.test]
name = "wasm-worker-test"
zone_id = "zone-test"
account_id = "account-test"
route = "https://test.site"
kv-namespaces = ...
```

Some people expressed concern about `kv-namespaces` being common to all environment, using that kind of configuration it can be different in each environment while maintaining the same JavaScript interface.

## Why arbitrary env?

I doubt we know everyone's workflow, we should let the user make Wrangler fit to their needs.

While we can't indentify which env is for prod (optimized) and dev (debug) I don't think it's an issue; Cloudflare's Worker is just a compilation target I think we should build for prod all the time. For debugging we could take advantage of source maps (or Wasm equivalent, if any).
