### ISSUE TITLE
New version message mismatch

### ISSUE THREAD

**Issue by lucasmezencio** [cloudflare/wrangler#2309]
#### Describe the bug

When running Wrangler v1, I'm getting the following message:

```
A new version of Wrangler (1.19.13) is available!
You can learn more about updating here:
https://developers.cloudflare.com/workers/cli-wrangler/install-update#update
```

However, when I try to update Wrangler, I get the following error:

```
npm i -g @cloudflare/wrangler@1.19.13 --update
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @cloudflare/wrangler@1.19.13.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Install `wrangler`
2. Run any `wrangler` command
3. See the new version message

#### Expected behavior

The latest version should be installed. Maybe NPM registry hasn't been updated?

#### Environment and versions

Fill out the following information about your environment.

* operating system:
```
❯ uname -a
Darwin hellsing-mbp.lan 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```
* output of `wrangler -V`:
```
❯ wrangler -V
wrangler 1.19.12
```
* output of `node -v`:
```
❯ node -v
v18.8.0
```
* content of `wrangler.toml`:
```toml
name = "workers-sites"
type = "webpack"
compatibility_date = "2022-03-30"
account_id = ""
zone_id = ""

workers_dev = false

[env.production]
route = "website.info/*"
kv_namespaces = [
    {binding = "ROCKET_KV", id = "***"}
]

[env.staging]
route = "dev2.website.info/*"
kv_namespaces = [
    {binding = "ROCKET_KV", id = "***"}
]
```
