### ISSUE TITLE
[[kv-namespaces]] in wrangler.toml throwing error

### ISSUE THREAD

**Issue by mrpatrick** [cloudflare/wrangler#415]
### 🐛 Bug Report
It seems like I must be doing something wrong, but I keep getting errors with the new kv-namespaces option for wrangler.toml as documented in the README.  Everything works fine if I remove `[[kv-namespaces]]` from wrangler.toml

#### Environment

* operating system: alpine
* output of `rustc -V`:
* output of `node -v`: 12.6.0

#### Steps to reproduce

wrangler.toml:
```toml
name = "MY_WORKER_NAME"
type = "webpack"
zone_id = "MY_ZONE_ID"
private = true
account_id = "MY_ACCOUNT_ID"
route = "MY_ROUTE"
[[kv-namespaces]]
binding = "MY_BINDING_NAME"
id = "MY_NAMESPACE_ID"
```

Run: `wrangler publish --release`

#### What did you expect to see?
```
⬇️ Installing wasm-pack...
⬇️ Installing wranglerjs...
 Built successfully.
🥳 Successfully published your script.
✨ Success! Your worker was successfully published. You can view it at ...
```

#### What did you see instead?
```
Error: ErrorMessage { msg: "⚠\u{fe0f} Your project config has an error, check your `wrangler.toml`: invalid type: map, expected a string for key `kv-namespaces[0]` in wrangler.toml" }
```
