### ISSUE TITLE
Specifying the `default` environment

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#442]
Suggestion: add a `default` boolean key that indicates which environment to use when no environment is passed to `preview` or `publish`.

e.g.
``` toml
[env.prod]
# ...
[env.staging]
default = true
# ...
```
would cause `$ wrangler publish` to use the `staging` environment. To publish to prod, the user would have to specifically pass the env, as in `$ wrangler publish --env=prod` This can help the ergonomics of a development cycle by preventing users from accidentally publishing to "prod" when they don't intend to. 

Alternative:
set a default for `preview` and `publish` rather than making default a bool.

``` toml
[env.prod]
# ...
[env.staging]
default = "publish"
# ...
[env.dev]
default = "preview"
# ...
```
would cause `$ wrangler publish` to use the `staging` environment, and `$ wrangler preview` to use the `dev` environment. This may or may not really help a thing, but it is rather common to have these three environments, and these are the two ways one might "push" things; in the case of workers that use KV, for example, you need to have your assets stored in KV for your worker to access them even from the preview service, so defining a 'dev' namespace for each developer would be a must-have for local previewing to work ergonomically.
