### ISSUE TITLE
Allow deploying to zoneless with environments

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#474]
### How do we specify an environment for a worker that will be deployed to workers.dev?

Here are a couple of ideas for when the behavior of `wrangler publish --environment dev` is intended to push a worker to workers.dev:

**1) zone_id and route are excluded**
```toml
[env.dev]
name = "wrangler-dev"
type = "webpack"
account_id = "e04d3d27a6829775c8ef937145d7f3ec"
```

**2) route is workers.dev (or includes it)**
```toml
[env.dev]
name = "wrangler-dev"
type = "webpack"
account_id = "e04d3d27a6829775c8ef937145d7f3ec"
route = "workers.dev"
```

**3) we specify that this environment is for workers.dev with a to-be-named boolean value**
```toml
[env.dev]
name = "wrangler-dev"
type = "webpack"
account_id = "e04d3d27a6829775c8ef937145d7f3ec"
somethingworkersdotdev = true
```

or something else entirely!

My thoughts are that 1 is a potential footgun because you could just forget some fields in your wrangler.toml and not expect your worker to be published to workers.dev
2 seems hacky
3 feels bad but maybe the best. I'm not sure what we should call the boolean in the toml.
