### ISSUE TITLE
[WIP] - prefixing and routes are confusing

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#691]
WIP: CURRENTLY TESTING THESE ASSUMPTIONS

one piece of feedback we received as part of today's QA: a user added `/w1` to the `route` config of their toml. They expected that the worker would then be able to find the asset they deployed from their bucket at `/index.html` when they navigated to `www.theusersdomain.com/w1`. Related: #675 

Setting aside for a moment the issues we have a few issues with leaky abstractions for routes, one possible solution for this would be to add a key `prefix` to the `site` configuration, and prepend the value there to the paths built out in the asset manifest that we send up with the worker. I think this is a relatively quick win that handles most issues, and works with our current model of encouraging users to push a single worker for a project and handle routing internally.

I can extend this to encompass the issues with routes that pre-date sites, but the above is easy and solves _most_ of the problem unique to this feature. A second issue can follow up around handling default routes from Wrangler, but I suspect this would require additional assumptions and API calls by Wrangler that are out of scope for the current milestone.

**Comment by EverlastingBugstopper** [comment]
+1 for adding `prefix` to site config

I'd also say that when deploying to a route that does not end in `/*` that we should throw a warning

**Comment by ashleymichal** [comment]
what i would like to work toward here is a world where `prefix` could make assumptions about `route` in the case of a zoned worker:

``` toml
account_id = ACCOUNT_ID
name = "site"
type = "webpack"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"

# Production
[env.production]
name = "site-prod"
route = "https://developers.cloudflare.com/workers*"
zone_id = ZONE_ID
```

could instead become

```toml
account_id = "95e065d2e3f97a1e50bae58aea71df6d"
name = "docs-site"
type = "webpack"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"
prefix = "/workers"

# Production
[env.production]
zone_id = ZONE_ID
```

For both zoned and zoneless workers, this would require appending the prefix (in this case `/workers`) to the paths in the asset manifest. This removes the necessity for the worker to trim this value as well.

For zoned workers, the assumption is that they only want their static site logic running on `/workers`, and their other paths should still pass through to the origin. In this case, we can populate their zone on their behalf, by getting the hostname for their zone from the API and appending their prefix as a route with a wildcard.

My only hesitation with the second implementation is that it feels like a bigger issue surrounding the way routes work on the platform and should likely be handled there, or in a larger route-targeted initiative.
