### ISSUE TITLE
Only install production dependencies in build step

### ISSUE THREAD

**Issue by minddust** [cloudflare/wrangler#938]
### 💡 Feature request

Only install production dependencies in build step

#### Overview and problem statement

Currently wrangler only runs `npm install`:
https://github.com/cloudflare/wrangler/blob/master/src/commands/build/wranglerjs/mod.rs#L240

But `npm install --production` would prevent some unnecessary installs (for eg prettifier) for the build step, which is also run via the publish command. locally it doesn't make a difference (cause the node folder already exists) but if you are deploying via github actions it will speed up the pipeline.

**Comment by minddust** [comment]
i had a longer discussion with a colleague and yes: this is a bit opinionated. 
normally you would put packages like webpack, typescript, .. into the devdependencies. 
which wouldn't compile with production only. 
in this special case (worker) i have all tools generating the worker artifact in my dependencies - test, linter etc are in devdeps. 
i just want wrangler to build and publish my worker without additional overhead. 

current workaround 

```yaml
    steps:
    - uses: actions/checkout@v1
    - name: Install node production packages
      run: cd workers-site && npm install --production
    - name: Deploy to Cloudflare Workers with Wrangler
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        environment: production
```
